[package]
name = "dji_tello_lib"
version = "0.1.0"
edition = "2021"
authors = ["Your Name"]
description = "Interactive command-line application for controlling DJI Tello drone"

[dependencies]
rustyline = "10.0.0"
dirs = "5.0.1"

[build-dependencies]
chrono = "0.4.31"
